# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa166c4be3c027dd6d5e692cd93977c23794656959a39390f31fbaca4e288d6efe0a7771d5477b0dce6bd156deab164450db87004756ed1b51b776970e94a1f

test:
  secret_key_base: 16a8d579a0aac8a829e424d09555fa1981669e697a1d6b1742b471e22a8a58c14c70128d9f487556f26a8f0317b5b5037052a94a41631331574d6f7bdb3a234e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
